image: docker:latest
services:
  - docker:dind

variables:
  DOCKER_DRIVER: overlay
  SPRING_PROFILES_ACTIVE: gitlab-ci

stages:
  - build
  - package

maven-build:
  image: maven:3-jdk-8
  stage: build
  script: "mvn package -B"
  artifacts:
    paths:
      - target/*.jar

docker-build:
  stage: package
  script:
  - docker login -u "ggermano2" -p  "Teste1234" docker.io
  - docker build -t ggermano2/springbootapisimples:latest
  - docker run -d -p8082:8082 ggermano2/springbootapisimples:latest 
